const express = require('express');
const fetch = require('node-fetch');
const fs = require('fs');
const path = require('path');
const { q } = require('./db');
const { requireAuth } = require('./middleware');
const { CODEGEN_SYSTEM, CODEGEN_ARCHITECT } = require('./prompts');

const CREATIONS_ROOT = path.resolve(__dirname, '..', 'data', 'creations');

// Write a generated project to disk under data/creations/<id>/ so the user
// has real files in the Replit project tree without ever opening the
// console. Hardened against path traversal: each file's resolved absolute
// path must stay under the creation directory.
function writeCreationToDisk(creationId, files) {
  const baseDir = path.join(CREATIONS_ROOT, String(creationId));
  fs.mkdirSync(baseDir, { recursive: true });
  const written = [];
  for (const f of files) {
    const target = path.resolve(baseDir, f.path);
    if (!target.startsWith(baseDir + path.sep) && target !== baseDir) continue;
    try {
      fs.mkdirSync(path.dirname(target), { recursive: true });
      fs.writeFileSync(target, f.content);
      written.push(f.path);
    } catch (_) { /* skip unwritable */ }
  }
  // Tiny manifest alongside the project, so it is obvious from the file
  // tree which build this was.
  try {
    const manifest = `Generated by Friday\nFiles: ${written.length}\n`;
    fs.writeFileSync(path.join(baseDir, '.friday-build.txt'), manifest);
  } catch (_) {}
  return { baseDir, written };
}

const router = express.Router();

const NIM_URL = process.env.NIM_URL || 'https://integrate.api.nvidia.com/v1/chat/completions';
const MODEL = process.env.CODEGEN_MODEL || 'qwen/qwen3-coder-480b-a35b-instruct';

const PER_CALL_TOKENS = 32768;  // per request (Qwen3-Coder-480B supports it)
const ARCHITECT_TOKENS = 12288; // larger budget for the manifest stage
const MAX_CONT_ROUNDS = 8;      // continuation rounds for the build stage
const MAX_RECOVERY_ROUNDS = 3;  // targeted missing-file/thin-file rounds
const MAX_FILES = 50;
const MAX_FILE_BYTES = 64 * 1024;
// Files smaller than this many bytes are treated as thin stubs and queued
// for recovery, unless they look like legitimate config stubs.
const THIN_FILE_BYTES = 180;
const CONFIG_STUB_RE = /(^|\/)(\.gitignore|\.env|\.env\.example|requirements\.txt|LICENSE|Procfile|\.npmrc|\.eslintrc(\.[^/]+)?)$/i;

// ---------- low-level model call ----------
async function callModelRaw(messages, maxTokens) {
  const r = await fetch(NIM_URL, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${process.env.NIM_KEY_CODEGEN}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      model: MODEL,
      messages,
      temperature: 0.2,
      top_p: 0.9,
      max_tokens: maxTokens,
      stream: false,
    }),
  });
  if (!r.ok) throw new Error(`upstream ${r.status}: ${(await r.text()).slice(0, 300)}`);
  const j = await r.json();
  return {
    content: j.choices?.[0]?.message?.content || '',
    finishReason: j.choices?.[0]?.finish_reason || 'stop',
  };
}

// Generate, automatically continuing when the model truncates on length.
// Concatenates the raw text across rounds so a project can exceed any single
// token budget. onRound(round) is called after each completed round.
async function generateWithContinuation(systemPrompt, userPrompt, onRound) {
  let full = '';
  let round = 0;
  while (round < MAX_CONT_ROUNDS) {
    round++;
    const messages = [{ role: 'system', content: systemPrompt }];
    if (full) {
      // Resume: give the model what it has produced and ask it to continue.
      messages.push({ role: 'user', content: userPrompt });
      messages.push({ role: 'assistant', content: full });
      messages.push({
        role: 'user',
        content: 'Continue exactly where you left off. Do not repeat any text you already emitted. Resume the current === FILE === block or start the next one, and finish all remaining files plus the trailing ENTRY/STACK/RUN/NOTES markers.',
      });
    } else {
      messages.push({ role: 'user', content: userPrompt });
    }
    const { content, finishReason } = await callModelRaw(messages, PER_CALL_TOKENS);
    full += content;
    if (onRound) onRound(round);
    if (finishReason !== 'length') break;
  }
  return full;
}

// ---------- parsers ----------
function parseBlocks(raw) {
  if (!raw || typeof raw !== 'string') return null;
  const text = raw.replace(/\r\n/g, '\n');
  const files = [];

  // Complete blocks.
  const fileRe = /=== FILE:\s*([^=\n]+?)\s*===\n([\s\S]*?)\n=== END FILE ===/g;
  let m;
  let lastEnd = 0;
  while ((m = fileRe.exec(text)) !== null) {
    const path = cleanPath(m[1]);
    if (path) files.push({ path, content: m[2] });
    lastEnd = fileRe.lastIndex;
  }

  // Salvage a final unterminated block (model stopped right at the edge).
  const tail = text.slice(lastEnd);
  const openRe = /=== FILE:\s*([^=\n]+?)\s*===\n([\s\S]*)$/;
  const om = tail.match(openRe);
  if (om && !/=== END FILE ===/.test(om[2])) {
    const path = cleanPath(om[1]);
    // Trim any trailing partial marker line.
    let content = om[2].replace(/\n?===[^\n]*$/, '');
    if (path && content.trim()) files.push({ path, content });
  }

  if (!files.length) return null;

  // Dedupe by path, keep the longest content (continuation may re-emit a header).
  const byPath = new Map();
  for (const f of files) {
    const prev = byPath.get(f.path);
    if (!prev || f.content.length > prev.content.length) byPath.set(f.path, f);
  }

  return {
    files: [...byPath.values()],
    entry: pick(text, 'ENTRY'),
    stack: pick(text, 'STACK'),
    run:   pick(text, 'RUN'),
    notes: pick(text, 'NOTES'),
  };
}

function pick(text, label) {
  const re = new RegExp('=== ' + label + ':\\s*([^=\\n]+?)\\s*===');
  const mm = text.match(re);
  return mm ? mm[1].trim() : '';
}

function cleanPath(p) {
  return String(p || '').trim().replace(/^\/+/, '').replace(/\.\.\//g, '').slice(0, 200);
}

// Parse the architect manifest.
function parseManifest(raw) {
  if (!raw) return null;
  const text = raw.replace(/\r\n/g, '\n');
  const filesBlock = text.match(/=== FILES ===\n([\s\S]*?)(?:\n=== END FILES ===|$)/);
  const files = [];
  if (filesBlock) {
    for (const line of filesBlock[1].split('\n')) {
      const t = line.trim();
      if (!t) continue;
      // "path — purpose" or "path - purpose" or just "path"
      const path = cleanPath(t.split(/\s+[—-]\s+/)[0].replace(/^[-*]\s*/, ''));
      if (path && /\.[a-z0-9]+$/i.test(path)) files.push(path);
    }
  }
  return {
    stack: pick(text, 'STACK'),
    run:   pick(text, 'RUN'),
    entry: pick(text, 'ENTRY'),
    notes: pick(text, 'NOTES'),
    files,
  };
}

// Backward-compat JSON envelope.
function extractJson(s) {
  if (!s) return null;
  const fenced = s.match(/```(?:json)?\s*([\s\S]*?)```/);
  if (fenced) s = fenced[1];
  const start = s.indexOf('{');
  const end = s.lastIndexOf('}');
  if (start === -1 || end === -1) return null;
  try { return JSON.parse(s.slice(start, end + 1)); } catch { return null; }
}

function pickEntry(files, explicit) {
  if (explicit && files.some(f => f.path === explicit)) return explicit;
  const preferences = [
    /^index\.html$/i, /^public\/index\.html$/i,
    /^main\.py$/i, /^app\.py$/i, /^app\/main\.py$/i,
    /^index\.js$/i, /^server\.js$/i, /^src\/index\.js$/i,
    /^src\/App\.jsx?$/i, /^main\.go$/i, /^src\/main\.rs$/i,
    /package\.json$/i, /^Cargo\.toml$/i,
  ];
  for (const re of preferences) {
    const hit = files.find(f => re.test(f.path));
    if (hit) return hit.path;
  }
  return files[0].path;
}

function sanitize(files) {
  return files
    .filter(f => f && typeof f.path === 'string' && typeof f.content === 'string' && f.content.trim().length > 0)
    .slice(0, MAX_FILES)
    .map(f => ({ path: cleanPath(f.path), content: f.content.slice(0, MAX_FILE_BYTES) }));
}

// ---------- SSE route ----------
router.post('/codegen', requireAuth, async (req, res) => {
  const goal = (req.body?.goal || '').toString().trim();

  res.setHeader('Content-Type', 'text/event-stream');
  res.setHeader('Cache-Control', 'no-cache, no-transform');
  res.setHeader('Connection', 'keep-alive');
  res.flushHeaders?.();
  const send = (obj) => res.write(`data: ${JSON.stringify(obj)}\n\n`);
  const fail = (error, raw) => {
    res.write(`event: error\ndata: ${JSON.stringify({ error, raw: (raw || '').slice(0, 600) })}\n\n`);
    res.end();
  };

  if (!process.env.NIM_KEY_CODEGEN) return fail('NIM_KEY_CODEGEN not set');
  if (!goal || goal.length < 4) return fail('goal required');

  let aborted = false;
  req.on('close', () => { aborted = true; });

  let raw = '';
  try {
    // ---- Stage A: architect / manifest ----
    send({ phase: 'planning' });
    const manifestRaw = await callModelRaw(
      [
        { role: 'system', content: CODEGEN_ARCHITECT },
        { role: 'user', content: `App goal: ${goal}` },
      ],
      ARCHITECT_TOKENS,
    ).then(r => r.content).catch(() => '');
    const manifest = parseManifest(manifestRaw) || { files: [], stack: '', run: '', entry: '', notes: '' };
    if (aborted) return;
    send({ phase: 'architecture', stack: manifest.stack, run: manifest.run, files: manifest.files });

    // ---- Stage B: build with continuation ----
    const manifestText = manifest.files.length
      ? `\n\nApproved manifest:\nSTACK: ${manifest.stack}\nRUN: ${manifest.run}\nENTRY: ${manifest.entry}\nFILES:\n${manifest.files.map(f => '- ' + f).join('\n')}\n\nEmit the complete content of every file above.`
      : '';
    const buildPrompt = `App goal: ${goal}${manifestText}`;
    raw = await generateWithContinuation(CODEGEN_SYSTEM, buildPrompt, (round) => {
      if (!aborted) {
        const partial = parseBlocks(raw + '');
        send({ phase: 'building', round, files: (partial?.files || []).map(f => f.path) });
      }
    });
    if (aborted) return;

    let parsed = parseBlocks(raw) || extractJson(raw);
    if (!parsed?.files?.length) return fail('model returned no parseable files', raw);
    parsed.files = sanitize(parsed.files);
    if (!parsed.files.length) return fail('model emitted only empty files', raw);

    // ---- Stage C: completeness check + recovery ----
    // A "needs recovery" file is either (a) listed in the manifest but
    // missing from the output, or (b) emitted with a suspiciously thin
    // body (under THIN_FILE_BYTES) that doesn't look like a config stub.
    // This catches the failure mode where the model wrote a one-line
    // placeholder for a planned file ("// TODO" or similar) and then
    // moved on, which used to slip past the simple presence check.
    if (manifest.files.length) {
      const byPath = () => new Map(parsed.files.map(f => [f.path, f]));
      const needsRecovery = () => {
        const m = byPath();
        const out = [];
        for (const p of manifest.files) {
          const f = m.get(p);
          if (!f) { out.push(p); continue; }
          if (f.content.length < THIN_FILE_BYTES && !CONFIG_STUB_RE.test(p)) {
            out.push(p);
          }
        }
        return out;
      };
      let needs = needsRecovery();
      let recovery = 0;
      while (needs.length && recovery < MAX_RECOVERY_ROUNDS && !aborted) {
        recovery++;
        send({ phase: 'verifying', missing: needs });
        const recPrompt = `App goal: ${goal}\n\nEmit ONLY these files, each COMPLETE and RUNNABLE with substantial real code (not a stub), in the === FILE: path === / === END FILE === format. Do not emit any other files.\n${needs.map(f => '- ' + f).join('\n')}`;
        const recRaw = await generateWithContinuation(CODEGEN_SYSTEM, recPrompt).catch(() => '');
        const recParsed = parseBlocks(recRaw);
        if (recParsed?.files?.length) {
          const have = byPath();
          for (const f of sanitize(recParsed.files)) {
            const prev = have.get(f.path);
            // Replace if it was missing OR was a thin stub the recovery
            // round improved on.
            if (!prev) { parsed.files.push(f); }
            else if (f.content.length > prev.content.length) {
              const idx = parsed.files.indexOf(prev);
              if (idx !== -1) parsed.files[idx] = f;
            }
          }
        }
        const stillNeeds = needsRecovery();
        if (stillNeeds.length === needs.length) break; // no progress
        needs = stillNeeds;
      }
    }
    if (aborted) return;

    // Fill metadata from manifest where the build omitted it.
    parsed.stack = parsed.stack || manifest.stack;
    parsed.run = parsed.run || manifest.run;
    parsed.notes = parsed.notes || manifest.notes;
    parsed.entry = pickEntry(parsed.files, parsed.entry || manifest.entry);

    const ins = q.addCreation.run(req.user.id, goal, JSON.stringify(parsed), Date.now());
    const creationId = ins?.lastInsertRowid;

    // Write the project to disk so the user has real files in the Replit
    // file tree — no console step required to extract a ZIP.
    let savedTo = null;
    try {
      const { baseDir } = writeCreationToDisk(creationId, parsed.files);
      // Report a path relative to the project root for readability
      savedTo = path.relative(path.resolve(__dirname, '..'), baseDir);
      send({ phase: 'saved', dir: savedTo, files: parsed.files.length });
    } catch (e) {
      // Disk-save is non-fatal — the user can still download via the ZIP.
      send({ phase: 'save-failed', error: e.message });
    }

    send({ phase: 'done', creationId, savedTo, ...parsed });
    res.write('event: done\ndata: {}\n\n');
    res.end();
  } catch (e) {
    if (!aborted) fail(e.message, raw);
  }
});

router.get('/history/creations', requireAuth, (req, res) => {
  const rows = q.recentCreations.all(req.user.id, 50).map(r => ({
    id: r.id, goal: r.goal, ts: r.ts,
  }));
  res.json({ creations: rows });
});

router.get('/creation/:id', requireAuth, (req, res) => {
  const row = q.creationById.get(Number(req.params.id), req.user.id);
  if (!row) return res.status(404).json({ error: 'not found' });
  try { res.json({ id: row.id, goal: row.goal, ts: row.ts, ...JSON.parse(row.files_json) }); }
  catch { res.status(500).json({ error: 'corrupt record' }); }
});

module.exports = { router };
